version: "3.8"

services:
  db:
    image: postgres:16
    container_name: ondo-postgres
    environment:
      POSTGRES_USER: ondo
      POSTGRES_PASSWORD: 1qazXSW@
      POSTGRES_DB: ondo_db
    ports:
      - "15432:5432"
    volumes:
      - /volume1/docker/ondo/db:/var/lib/postgresql/data
    restart: always

  backend:
    image: jongmin402/ondo-backend:latest
    pull_policy: never
    container_name: ondo-backend
    ports:
      - "3000:3000"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - DB_HOST=db
      - PORT=3000
    volumes:
      - /volume1/docker/ondo/uploads:/app/uploads
    depends_on:
      - db
    restart: always

  frontend:
    image: ondo-frontend:latest
    container_name: ondo-frontend
    ports:
      - "8081:80"
    depends_on:
      - backend
    restart: always
